services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ngocphuoce_hai
      MYSQL_USER: ngocphuoce_hai
      MYSQL_PASSWORD: QnsY9uaH
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./ngocphuoce_hai.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
