<div id="advanced-newsletter-box">
    <div class="input-group box-newsletter-subscribe" id="mail-box">
        <input type="text" name="email" placeholder="<?php echo $text_placeholder_input; ?>"/>
        <span class="input-group-btn">
        <button class="btn btn-primary enter-subscribe" type="button"><i class="fa fa-envelope-o" style="margin-right:5px;"></i></button>
        </span>
    </div>
</div>
<script type="text/javascript">
    new AdvancedNewsletter({
        container_id: '#advanced-newsletter-box',
        input_id: 'input[name=email]',
        submit_id: '.enter-subscribe'
    });
</script>